apiVersion: v1
kind: Namespace
metadata:
    name: peerorg2-demo

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: peerorg2-demo-pv
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /crypto-config/peerOrganizations/peerorg2-demo
    server: fs-f86463b3.efs.us-east-1.amazonaws.com
  storageClassName: aws-efs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 namespace: peerorg2-demo
 name: peerorg2-demo-pv
 annotations:
  volume.beta.kubernetes.io/storage-class: aws-efs
spec:
 accessModes:
   - ReadWriteMany
 resources:
   requests:
     storage: 10Mi

---
