apiVersion: v1
kind: Namespace
metadata:
    name: $org

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: $pvName
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  nfs:
    path: $path
    server: fs-f86463b3.efs.us-east-1.amazonaws.com
  storageClassName: aws-efs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 namespace: $org
 name: $pvName
 annotations:
  volume.beta.kubernetes.io/storage-class: aws-efs
spec:
 accessModes:
   - ReadWriteMany
 resources:
   requests:
     storage: 10Mi

---
