apiVersion: v1
kind: Namespace
metadata:
    name: org1

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: org1-pv
  labels:
    name: org1-pv
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /opt/share/crypto-config/peerOrganizations/org1
    server: 13.234.19.253
    #server: fs-ed2327a6.efs.us-east-1.amazonaws.com
  #change to your nfs server ip here
  storageClassName: gp2

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: org1
  name: org1-pv
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Mi
  selector:
     matchLabels:
       name: org1-pv
---
