OrdererOrgs:
  - Name: Orderer1
    Domain: orgorderer1
    Template:
      Count: 1

PeerOrgs:
  - Name: Org1
    Domain: org1
    Template:
      Count: 2
    Users:
      Count: 1



