apiVersion: v1
kind: PersistentVolume
metadata:
  name: npm-data
  labels:
    name: npm-data
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /
    server: fs-a230fcbb.efs.us-west-1.amazonaws.com #change to your nfs server ip here
  storageClassName: aws-efs
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    namespace: default
    name: npm-data
    annotations:
        volume.beta.kubernetes.io/storage-class: aws-efs
spec:
   accessModes:
     - ReadWriteMany
   resources:
      requests:
        storage: 200Mi
   selector:
    matchLabels:
      name: npm-data

