apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: org1
  name:	peer0-org1
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
       app: hyperledger
       role: peer
       peer-id: peer0
       org: org1
       product: stemcell
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: product
                operator: In
                values:
                - stemcell
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: couchdb
        image: 13.127.243.52:5000/hyperledger/fabric-couchdb:x86_64-1.0.0
        ports:
         - containerPort: 5984
      - name: peer0-org1 
        image: 13.127.243.52:5000/hyperledger/fabric-peer:x86_64-1.1.0
        env:
        - name: CORE_LEDGER_STATE_STATEDATABASE
          value: "CouchDB"
        - name: CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS
          value: "localhost:5984"
#          value: "production-couch.aob-stemcell-private.local:5984"
       # - name: CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME
       #   value: "admin"
       # - name: CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
       #   value: "aobcdb321*77"
        - name: CORE_VM_ENDPOINT
          value: "unix:///host/var/run/docker.sock"
        - name: CORE_LOGGING_LEVEL
          value: "DEBUG"
        - name: CORE_PEER_TLS_ENABLED
          value: "false"
        - name: CORE_PEER_GOSSIP_USELEADERELECTION
          value: "true"
        - name: CORE_PEER_GOSSIP_ORGLEADER
          value: "false" 
        - name: CORE_PEER_PROFILE_ENABLED
          value: "true"
        - name: CORE_PEER_TLS_CERT_FILE
          value: "/etc/hyperledger/fabric/tls/server.crt" 
        - name: CORE_PEER_TLS_KEY_FILE
          value: "/etc/hyperledger/fabric/tls/server.key"
        - name: CORE_PEER_TLS_ROOTCERT_FILE
          value: "/etc/hyperledger/fabric/tls/ca.crt"
        - name: CORE_PEER_ID
          value: peer0.org1
        - name: CORE_PEER_ADDRESS
          value: peer0.org1:7051
        - name: CORE_PEER_GOSSIP_EXTERNALENDPOINT
          value: peer0.org1:7051
        - name: CORE_PEER_LOCALMSPID
          value: Org1MSP
        - name: CORE_PEER_ADDRESSAUTODETECT
          value: "true"
        - name: CORE_CHAINCODE_STARTUPTIMEOUT
          value: "1200s"
        - name: CORE_CHAINCODE_EXECUTETIMEOUT
          value: "1200s"
#        - name: CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE
#          value: "host"
        workingDir: /opt/gopath/src/github.com/hyperledger/fabric/peer
        ports:
         - containerPort: 7051
         - containerPort: 7052
         - containerPort: 7053
        command: ["peer"]
        args: ["node","start"]
        volumeMounts:
         #- mountPath: /opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts 
         #  name: certificate
         #  subPath: channel-artifacts
         - mountPath: /etc/hyperledger/fabric/msp 
           name: certificate
           #subPath: crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/msp
           subPath: peers/peer0.org1/msp
         - mountPath: /etc/hyperledger/fabric/tls
           name: certificate
           #subPath: crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/
           subPath: peers/peer0.org1/tls
         - mountPath: /host/var/run/
           name: run
#         - mountPath: /etc/hyperledger/fabric/core.yaml
#           name: core
#         - mountPath: /var/hyperledger/production/
#           name: production
         - mountPath: /var/hyperledger/production/
           name: production-data
           subPath: peer0.org1
      volumes:
       - name: certificate
         persistentVolumeClaim:
             claimName: org1-pv
       - name: run
         hostPath:
           path: /var/run
#       - name: core
#         hostPath:
#           path: /opt/share/core-config/core.yaml
#       - name: production
#         hostPath:
#           path: /var/hyperledger/production/peer0.org1
       - name: production-data
         persistentVolumeClaim:
             claimName: production-data

---
apiVersion: v1
kind: Service
metadata:
   namespace: org1
   name: peer0
spec:
 selector:
   app: hyperledger
   role: peer
   peer-id: peer0
   org: org1
 type: NodePort
 ports:
   - name: externale-listen-endpoint
     protocol: TCP
     port: 7051
     targetPort: 7051
     nodePort: 30001

   - name: chaincode-listen
     protocol: TCP
     port: 7052
     targetPort: 7052
     nodePort: 30002

   - name: event-listen
     protocol: TCP
     port: 7053
     targetPort: 7053
---

